### ISSUE TITLE
Export all open task to a specific email

### ISSUE THREAD

**Issue by korlikiangel** [creecros/SendEmailCreator#19]
Hi,

It would be very helpful to be able to backup open tasks to a .csv file sent to a specific email.

Currently I have to do this manually by Exporting and saving the file on my computer. An automatic action that would send such a file to an email would significantly improve the quality of work.

Additionally, is it possible in such a solution that exported file would contain metadata?

I wrote a similar request on kanboard's github, but I see that this plugin already contains part of that solution I wrote about earlier.

**Comment by creecros** [comment]
I dont see why either of those things wouldn't be possible. I wouldn't add said things to this plugin tho. seems very specific of a task more closely related to metamagik since that's really the only place one would likely care about metadata, and MetaMagik already has a custom built export function to include custom fields.

**Comment by creecros** [comment]
also, not seeing "attachments" as having ever been addressed in Kanboard core. It uses Swiftmailer, which is capable of adding attachments, but if you go through the core mailer transport, there is no way to do it, since the parameter for it is non existent:
https://github.com/kanboard/kanboard/blob/8ddd32f0cb15fe7f2147754f91f9a8421853c1ae/app/Core/Mail/Transport/Mail.php#L31-L58

so you would have to build your own mailer with the parameter for attachments added. again, doable, but for this plugin, it is really only meant to be an action pack, containing basic actions, there would be a lot of "things" that would need to be added, to make this even work, things that i wouldn't put into this plugin of simple actions.
